import { Lato } from "next/font/google";
import { GoogleAnalytics } from "@next/third-parties/google";
import Link from "next/link";

import "../styles/globals.scss";

const lato = Lato({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-lato",
  display: "swap",
});

export const metadata = {
  metadataBase: new URL("https://rbcpcpreschool.org"),
  title: {
    default: "RBCPC Preschool",
    template: "%s - RBCPC Preschool",
  },
  description: "Generated by create next app",
  alternates: {
    canonical: "./",
  },
  // openGraph: {
  //   url: "https://rbcpcpreschool.org",
  //   images: [
  //     {
  //       url: "/images/rbcpcPreschoolOG.jpg",
  //       width: 1200,
  //       height: 630,
  //       alt: "RBCPC Preschool",
  //     },
  //   ],
  //   type: "website",
  // },
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body className={lato.variable}>
        {children}
        {modal}
      </body>
      <GoogleAnalytics gaId="G-FQ31JPPR0K" />
    </html>
  );
}
